# Generated by Django 5.0.6 on 2024-06-04 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pasticceria', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField(unique=True, verbose_name='Código')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('descripcion', models.CharField(max_length=100, verbose_name='Descripción')),
                ('categorias', models.CharField(max_length=100, unique=True, verbose_name='Categorías')),
                ('precio', models.IntegerField(verbose_name='Precio')),
                ('rating', models.CharField(max_length=100, verbose_name='Rating')),
                ('inventario', models.IntegerField(verbose_name='Inventario')),
            ],
        ),
        migrations.CreateModel(
            name='Vendedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField(unique=True, verbose_name='Código')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=100, verbose_name='Apellido')),
                ('dni', models.IntegerField(unique=True, verbose_name='DNI')),
            ],
        ),
    ]
