# Generated by Django 5.0.6 on 2024-06-06 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pasticceria', '0003_orden_ordenitem_orden_productos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='rating',
        ),
        migrations.AlterField(
            model_name='producto',
            name='descripcion',
            field=models.CharField(max_length=200, verbose_name='Descripción'),
        ),
    ]
