# Generated by Django 5.0.6 on 2024-06-09 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pasticceria', '0005_remove_producto_inventario_producto_existencias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='categorias',
            field=models.CharField(max_length=100, verbose_name='Categorías'),
        ),
    ]
