# Generated by Django 5.0.6 on 2024-06-09 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pasticceria', '0006_alter_producto_categorias'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='telefono',
            field=models.CharField(max_length=15, null=True, verbose_name='Telefono'),
        ),
    ]
